<a href="https://colab.research.google.com/github/FiahIdris/GColab_Learning/blob/main/NLP_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam Detection using Naive Bayes

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
corpus = [
          "Saya sedang belajar data science",
          "Data Science adalah disiplin ilmu yang baru",
          "Saya menggunakan Python untuk melakukan pemrosesan data"
]

In [ ]:
vect = CountVectorizer()
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
vect.get_feature_names()

['adalah',
 'baru',
 'belajar',
 'data',
 'disiplin',
 'ilmu',
 'melakukan',
 'menggunakan',
 'pemrosesan',
 'python',
 'saya',
 'science',
 'sedang',
 'untuk',
 'yang']

In [ ]:
corpus_vect = vect.transform(corpus)

In [ ]:
corpus_vect

<3x15 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [ ]:
corpus_vect.toarray()

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0]])

In [ ]:
pd.DataFrame(corpus_vect.toarray(), columns=vect.get_feature_names())

adalah  baru  belajar  data  disiplin  ...  saya  science  sedang  untuk  yang
0       0     0        1     1         0  ...     1        1       1      0     0
1       1     1        0     1         1  ...     0        1       0      0     1
2       0     0        0     1         0  ...     1        0       0      1     0

[3 rows x 15 columns]

In [ ]:
new_sent = ['saya belajar nlp']
new_sent_vect = vect.transform(new_sent)
pd.DataFrame(new_sent_vect.toarray(), columns=vect.get_feature_names())

adalah  baru  belajar  data  disiplin  ...  saya  science  sedang  untuk  yang
0       0     0        1     0         0  ...     1        0       0      0     0

[1 rows x 15 columns]

# Implementasi Model Machine Learning

In [ ]:
! pip install pysastrawi

     |████████████████████████████████| 210 kB 5.0 MB/s 


In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/afifai/hacktiv8-trial-class-spamdetector/main/data/dataset_sms_spam%20_v1.csv")
df.head()

Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...      2
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...      2
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...      2

In [ ]:
df.label = df.label.map({0:"SMS Biasa", 1:"SMS Penipuan", 2:"SMS Operator"})

In [ ]:
df.label.value_counts()

SMS Biasa       569
SMS Penipuan    335
SMS Operator    239
Name: label, dtype: int64

In [ ]:
# split data
X_train, X_test, y_train, y_test = train_test_split(df.Teks, df.label, test_size=0.2)

In [ ]:
stp = StopWordRemoverFactory().get_stop_words()
vect = CountVectorizer()

In [ ]:
X_train_vec = vect.fit_transform(X_train)
X_test_vec = vect.transform(X_test)

In [ ]:
X_train_vec

<914x4340 sparse matrix of type '<class 'numpy.int64'>'
	with 15375 stored elements in Compressed Sparse Row format>

In [ ]:
X_test_vec

<229x4340 sparse matrix of type '<class 'numpy.int64'>'
	with 3163 stored elements in Compressed Sparse Row format>

In [ ]:
# training naive bayes
nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
# evaluasi
y_pred = nb.predict(X_test_vec)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   SMS Biasa       0.98      0.94      0.96       121
SMS Operator       0.89      0.98      0.94        52
SMS Penipuan       0.93      0.93      0.93        56

    accuracy                           0.95       229
   macro avg       0.94      0.95      0.94       229
weighted avg       0.95      0.95      0.95       229



In [ ]:
# inference
sms_baru = [
            "hai bro, apa kabar ?",
            "dapatkan kuota 1 GB per hari hanya Rp. 1000 dari aplikasi MyGSM",
            "pesugihan halal, lipatgandakan uang anda dan lunasi hutang-hutang anda bersama saya"
]

In [ ]:
sms_baru_vect = vect.transform(sms_baru)
nb.predict(sms_baru_vect)

array(['SMS Biasa', 'SMS Operator', 'SMS Penipuan'], dtype='<U12')

# Implementasi dengan Deep Learning

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/afifai/hacktiv8-trial-class-spamdetector/main/data/dataset_sms_spam%20_v1.csv")
df.head()

Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...      2
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...      2
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...      2

In [ ]:
train_df, test_df = train_test_split(df, test_size=0.2)

In [ ]:
train_df.shape

(914, 2)

In [ ]:
test_df.shape

(229, 2)

In [ ]:
import random
random_index = random.randint(0, len(train_df) - 5)
for row in train_df[["Teks", "label"]][random_index:random_index + 5].itertuples():
  _, text, target = row
  if target == 0:
    print(f"Target: {target} (SMS BIASA)")
  elif target == 1:
    print(f"Target: {target} (SMS PENIPUAN)")
  elif target == 2:
    print(f"Target: {target} (SMS PROMOSI)")
  print(f"Teks: {text}\n")
  print("---\n")

Target: 0 (SMS BIASA)
Teks: Eh di kosan nama1 maksudnya, buat temen nama1 , buat september

---

Target: 0 (SMS BIASA)
Teks: Yg mau ngampus aku pengen titip bawain SKL aku di prodi😭

---

Target: 1 (SMS PENIPUAN)
Teks: Kak, kirimkan dulu pulsa25rb di no baruku ini 085377771822

---

Target: 2 (SMS PROMOSI)
Teks: Rp30rb/bln utk 3 bln (hrg normal Rp59rb utk bln ke-4 dst) bisa NELPON & SMS SEPUASNYA ke IM3 plus kuota 3GB+10GB (4G).  Mau? Ketik YA ke 919 sd 05-Aug-16

---

Target: 1 (SMS PENIPUAN)
Teks: Maaf saya Bu Nur, tanah yang di tanjung api-api saya sudah lihat dan sudah cocok, untuk masalah harga tolong hubungi suami saya aja, pak H.SULAIMAN di no hp. 08xxxxxx, karena kebetulan saya ada acara.Tks

---



In [ ]:
# siapkan target
from tensorflow.keras.utils import to_categorical

X_train, y_train = train_df.Teks, train_df.label
X_test, y_test = test_df.Teks, test_df.label

def prepare_target(y_train, y_test):
  y_train_enc = to_categorical(y_train)
  y_test_enc = to_categorical(y_test)
  return y_train_enc, y_test_enc

y_train, y_test = prepare_target(y_train, y_test)

In [ ]:
# split train-val
train_sent, val_sent, train_labels, val_labels = train_test_split(X_train.to_numpy(),
                                                                   y_train,
                                                                   test_size=0.2)

In [ ]:
train_sent[:10], train_labels[:10]

(array(['Makasih gais doakan kami yg masih berjuang ya 💪',
        'Transfer saja uangnya ke rek ini.mandiri.NO Rek: 152-00-1236312-9.a/n:DARMAN. klau sdah di Transfer SMS saja ke nmor ini Trima kasih',
        'Kalo engga belakang aqila ada 600/bulan gatau masih apa engga deh',
        'Rp30rb/bln utk 3 bln (hrg normal Rp59rb utk bln ke-4 dst) bisa NELPON & SMS SEPUASNYA ke IM3 plus kuota 3GB+10GB (4G). \xa0Mau? Ketik YA ke 919 sd 05-Aug-16',
        'Surat Keputusan PT.TRI.3 Slamat No.08966xxx Resmi M-dptkan HONDA JAZZ Rs KODE Pin:477BFG7S Info Hub:08606490199 KLIK: www.hadiah-tricare.com',
        'kita lewat kolam renang? di gymnas atau gik',
        'Patah hatinya level tinggi, jd bisa quotes begitu put',
        'Ka aku ga bisa liat kosannya skrg :( soalnya ngerjain uts take home ka ',
        'Asal pagi pagi ya.. Bjam 10an saya sudah ke jakarta..',
        'Mohon maaf lahir dan batin ipa3😚😚'], dtype=object),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
     

## Tokenisasi

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [ ]:
round(sum([len(i.split()) for i in train_sent])/len(train_sent))

16

In [ ]:
# setup text vect
max_vocab_length = 4000
max_length = 17

text_vectorization = TextVectorization(max_tokens=max_vocab_length,
                                       standardize="lower_and_strip_punctuation",
                                       split="whitespace",
                                       ngrams=None,
                                       output_mode='int',
                                       output_sequence_length=max_length)

In [ ]:
# vektorisasi teks
text_vectorization.adapt(train_sent)

In [ ]:
# sms baru
sample_sms = "selamat no anda memenangkan undian berhadiah babi ngepet"
text_vectorization([sample_sms])

<tf.Tensor: shape=(1, 17), dtype=int64, numpy=
array([[  31,   13,    3, 2416,   84, 3344,    1,    1,    0,    0,    0,
           0,    0,    0,    0,    0,    0]])>

In [ ]:
text_vectorization.get_vocabulary()[0]

''

In [ ]:
random_sms = random.choice(train_sent)
print(f"Teks Asli : {random_sms}\n")
text_vectorization([random_sms])

Teks Asli : Oh pantesan tau gitu lgsg foto dipusatnya aja put



<tf.Tensor: shape=(1, 17), dtype=int64, numpy=
array([[ 680, 2171,  181,  353,  543, 1159, 3085,   17,  505,    0,    0,
           0,    0,    0,    0,    0,    0]])>

## Buat Embedding Layer

In [ ]:
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim=max_vocab_length,
                             output_dim=128,
                             embeddings_initializer="uniform",
                             input_length=max_length)

embedding

In [ ]:
random_sms = random.choice(train_sent)
print(f"Teks Asli : {random_sms}\n")

sample_embedded = embedding(text_vectorization([random_sms]))
sample_embedded.shape

Teks Asli : Terimakasih, saat ini Anda masih terdaftar sebagai pelanggan TCash.



TensorShape([1, 17, 128])

## Pemodelan

In [ ]:
# fc NN

inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorization(inputs)
x = embedding(x)
x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(3, activation='softmax')(x)
model_1 = tf.keras.Model(inputs, outputs, name='model_nlp_fc')

In [ ]:
# compile model
model_1.compile(loss='categorical_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
model_1.summary()

Model: "model_nlp_fc"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
text_vectorization_1 (TextVe (None, 17)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 17, 128)           512000    
_________________________________________________________________
global_average_pooling1d_2 ( (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 387       
Total params: 512,387
Trainable params: 512,387
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model_1_hist = model_1.fit(train_sent,
                           train_labels,
                           epochs=5,
                           validation_data=(val_sent, val_labels))

Epoch 1/5
23/23 [==============================] - 1s 21ms/step - loss: 1.0560 - accuracy: 0.6648 - val_loss: 0.9985 - val_accuracy: 0.7377
Epoch 2/5
23/23 [==============================] - 0s 10ms/step - loss: 0.9282 - accuracy: 0.8878 - val_loss: 0.8814 - val_accuracy: 0.8197
Epoch 3/5
23/23 [==============================] - 0s 9ms/step - loss: 0.7811 - accuracy: 0.9056 - val_loss: 0.7485 - val_accuracy: 0.8689
Epoch 4/5
23/23 [==============================] - 0s 10ms/step - loss: 0.6291 - accuracy: 0.9302 - val_loss: 0.6271 - val_accuracy: 0.8798
Epoch 5/5
23/23 [==============================] - 0s 9ms/step - loss: 0.5010 - accuracy: 0.9412 - val_loss: 0.5334 - val_accuracy: 0.8798


In [ ]:
model_1.evaluate(val_sent, val_labels)

6/6 [==============================] - 0s 2ms/step - loss: 0.5334 - accuracy: 0.8798


[0.5334129333496094, 0.8797814249992371]

In [ ]:
res = model_1.predict(val_sent)[:10]

In [ ]:
res.argmax(axis=1)

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
val_sent[:10]

array(['dapatkan total hadiah ratusan juta rupiah di Kota 1000 Berkah. Caranya? Klik www.murahituim3.com/kota1000berkah Program s.d 9 Agustus 2013',
       'Nanti kalau mau di bayar/di transfer harap hubungi dulu atasan saya Bpk ARDIANSA no tlp; 085797136879 soalnya ada perubahan pembayaran trima kasih.',
       'Ada nama1 . Tpi gatau msh berfungsi atau engga, udh lama ga dipake sih',
       'SLMT!! No Anda men-dpt hadiah dr:pengundian PT.TELKOMSEL No pin b89c7... Untuk melihat Hadiah Anda, silakan klik : www.telkomselpoin2222.webs.com',
       'Ini ini udh disini mau apa aku gorengin',
       'Mau sekalian dibawain kacamata ga, nanti aku keluar jam 10',
       'Januari mah ambil 1x seminggu aja. Kan kita masuk seminggu sekali kalau januari.',
       'silahkan berkas dambil di ruang saya',
       'Besok dwm jadi ya praktikum weka. Bawa laptop.',
       'iya, makanya aku butuh data kalian teh soalnya datanya dari sana. tapi harus ada RJ atau RD.'],
      dtype=object)

In [ ]:
# inference data baru

sms_baru = [
            "hai bro, apa kabar ?",
            "dapatkan kuota 1 GB per hari hanya Rp. 1000 dari aplikasi MyGSM",
            "pesugihan halal, lipatgandakan uang anda dan lunasi hutang-hutang anda bersama saya"
]

hasil = model_1.predict(sms_baru)
hasil.argmax(axis=1)

array([0, 0, 0])

## LSTM

In [ ]:
inputs = layers.Input(shape=(1,), dtype='string')
x = text_vectorization(inputs)
x = embedding(x)
x = layers.LSTM(64)(x)
outputs = layers.Dense(3, activation='softmax')(x)
model_2 = tf.keras.Model(inputs, outputs, name="LSTM_model")

In [ ]:
model_2.summary()

Model: "LSTM_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
text_vectorization_1 (TextVe (None, 17)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 17, 128)           512000    
_________________________________________________________________
lstm (LSTM)                  (None, 64)                49408     
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 195       
Total params: 561,603
Trainable params: 561,603
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# compile model
model_2.compile(loss='categorical_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
model_2_hist = model_2.fit(train_sent,
                           train_labels,
                           epochs=5,
                           validation_data=(val_sent, val_labels))

Epoch 1/5
23/23 [==============================] - 3s 46ms/step - loss: 0.6731 - accuracy: 0.7551 - val_loss: 0.4801 - val_accuracy: 0.7650
Epoch 2/5
23/23 [==============================] - 1s 22ms/step - loss: 0.2058 - accuracy: 0.9384 - val_loss: 0.2591 - val_accuracy: 0.9126
Epoch 3/5
23/23 [==============================] - 1s 23ms/step - loss: 0.0661 - accuracy: 0.9808 - val_loss: 0.2538 - val_accuracy: 0.9344
Epoch 4/5
23/23 [==============================] - 1s 22ms/step - loss: 0.0377 - accuracy: 0.9891 - val_loss: 0.2671 - val_accuracy: 0.9344
Epoch 5/5
23/23 [==============================] - 1s 23ms/step - loss: 0.0205 - accuracy: 0.9959 - val_loss: 0.2971 - val_accuracy: 0.9235


In [ ]:
# inference data baru

sms_baru = [
            "hai bro, apa kabar ?",
            "dapatkan kuota 1 GB per hari hanya Rp. 1000 dari aplikasi MyGSM",
            "pesugihan halal, lipatgandakan uang anda dan lunasi hutang-hutang anda bersama saya"
]

hasil = model_2.predict(sms_baru)
hasil.argmax(axis=1)

array([0, 2, 1])

## GRU


In [ ]:
inputs = layers.Input(shape=(1,), dtype='string')
x = text_vectorization(inputs)
x = embedding(x)
x = layers.GRU(64)(x)
outputs = layers.Dense(3, activation='softmax')(x)
model_3 = tf.keras.Model(inputs, outputs, name="GRU_model")

In [ ]:
# compile model
model_3.compile(loss='categorical_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
model_3.summary()

Model: "GRU_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
text_vectorization_1 (TextVe (None, 17)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 17, 128)           512000    
_________________________________________________________________
gru (GRU)                    (None, 64)                37248     
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 195       
Total params: 549,443
Trainable params: 549,443
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model_3_hist = model_3.fit(train_sent,
                           train_labels,
                           epochs=5,
                           validation_data=(val_sent, val_labels))

Epoch 1/5
23/23 [==============================] - 3s 43ms/step - loss: 0.7426 - accuracy: 0.7921 - val_loss: 0.5689 - val_accuracy: 0.8033
Epoch 2/5
23/23 [==============================] - 1s 22ms/step - loss: 0.2677 - accuracy: 0.9343 - val_loss: 0.2642 - val_accuracy: 0.9126
Epoch 3/5
23/23 [==============================] - 1s 22ms/step - loss: 0.0398 - accuracy: 0.9918 - val_loss: 0.3286 - val_accuracy: 0.9290
Epoch 4/5
23/23 [==============================] - 1s 22ms/step - loss: 0.0145 - accuracy: 0.9973 - val_loss: 0.2880 - val_accuracy: 0.9290
Epoch 5/5
23/23 [==============================] - 0s 21ms/step - loss: 0.0099 - accuracy: 0.9959 - val_loss: 0.3049 - val_accuracy: 0.9126


In [ ]:
# inference data baru

sms_baru = [
            "hai bro, apa kabar ?",
            "dapatkan kuota 1 GB per hari hanya Rp. 1000 dari aplikasi MyGSM",
            "pesugihan halal, lipatgandakan uang anda dan lunasi hutang-hutang anda bersama saya"
]

hasil = model_3.predict(sms_baru)
hasil.argmax(axis=1)

array([0, 2, 1])